src/app/fleet/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView
from app.fleet import views

urlpatterns = [
    # url(r'^$', views.FleetList.as_view(), name='list'),
    # url(r'^cadastrar$', views.FleetCreate.as_view(), name='create'),
    # url(r'^editar/(?P<pk>[0-9]+)$', views.FleetUpdate.as_view(),
    #     name='update'),
]

src/app/rentacar/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from app.rentacar import views

urlpatterns = [
    url(r'^alugar$', login_required(views.RentACarView.as_view()),
        name='create'),
    url(r'^devolver$', login_required(views.RentACarGiveBackView.as_view()),
        name='give-back'),
]

src/lemonade/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from app.core.views import Home

# handler500 = 'app.core.views.page_500'
handler404 = 'app.core.views.page_404'
handler403 = 'app.core.views.page_403'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^clientes/', include('app.customer.urls', namespace='customer')),
    url(r'^administracao/', include('app.dashboard.urls',
        namespace='dashboard')),
    url(r'^frota/', include('app.fleet.urls', namespace='fleet')),
    url(r'^aluguel/', include('app.rentacar.urls', namespace='rentacar')),
    url(r'^login$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/'},
        name='logout'),
    url(r'^api/v1', include('app.api.v1.urls', namespace='api-v1')),
    url(r'^$', Home.as_view(), name='index'),
]

src/app/fleet/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from app.core.flags import CATEGORY_CHOICES


class Fleet(models.Model):

    class Meta:
        app_label = u'fleet'
        verbose_name = 'Frota'
        verbose_name_plural = 'Frotas'

    vehicle_name = models.CharField(verbose_name=u'Nome', max_length=255)
    category = models.CharField(verbose_name=u'Categoria', max_length=10,
        choices=CATEGORY_CHOICES)
    description = models.TextField(verbose_name=u'Descrição', max_length=1000,
        null=True, blank=True)
    is_rented = models.BooleanField(verbose_name=u'Está alugado?',
        default=False)

    def _validate_cnh_type(self, customer):
        can_rent = False

        if self.category == 'motorcycle' and 'A' in customer.cnh_type:
            can_rent = True
        elif self.category == 'car' and 'B' in customer.cnh_type:
            can_rent = True
        elif self.category == 'utility' and 'C' in customer.cnh_type:
            can_rent = True
        elif (self.category == 'truck' and
            ('D' in customer.cnh_type or 'E' in customer.cnh_type)):
            can_rent = True

        return can_rent

    def can_rent(self, customer):
        if not self.is_rented:
            return self._validate_cnh_type(customer)

    def __unicode__(self):
        return self.vehicle_name

src/app/api/v1/fleet/views.py
# -*- coding: utf-8 -*-


from rest_framework import viewsets
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from app.api import mixins
from app.api.v1.fleet.serializers import FleetSerializer
from app.api.v1.fleet.serializers import FleetRetrieveSerializer
from app.fleet.models import Fleet


# class FleetView(viewsets.ViewSet, mixins.ListMixin):
class FleetView(viewsets.ViewSet):

    serializer_class = FleetSerializer
    serializer_class_retrieve = FleetRetrieveSerializer

    # def get_queryset(self):
    #     return Fleet.objects.all()

    def get_single_object(self, pk):
        return get_object_or_404(Fleet.objects.all(), pk=pk)

    def create(self, request):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            serializer.save()

            return self.retrieve(request, pk=serializer.instance.id)

        return Response(serializer.errors)

    def update(self, request, pk=None, partial=None):
        obj = self.get_single_object(pk)
        serializer = self.serializer_class(data=request.data, instance=obj,
            partial=partial)

        if serializer.is_valid():
            serializer.save()

            return self.retrieve(request, pk=serializer.instance.id)

        return Response(serializer.errors)

    def partial_update(self, request, pk=None):
        return self.update(request, pk=pk, partial=True)

    def destroy(self, request, pk=None):
        obj = self.get_single_object(pk)
        obj.delete()

        return Response({'detail': 'Veículo excluído com sucesso.'})

    # def list(self, request):
    #     from rest_framework.pagination import Response as ResponseList
    #     serializer = self.serializer_class(Fleet.objects.all())

    #     return ResponseList(serializer.data)

    def retrieve(self, request, pk=None):
        obj = self.get_single_object(pk)
        serializer = self.serializer_class_retrieve(obj)

        return Response(serializer.data)

src/app/fleet/views.py
# -*- coding: utf-8 -*-

from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied

from app.fleet.models import Fleet


# class FleetBaseView(object):

#     @method_decorator(login_required)
#     def dispatch(self, *args, **kwargs):
#         if not self.request.user.has_perms(['fleet.add_fleet',
#             'fleet.change_fleet', 'fleet.delete_fleet']):

#             raise PermissionDenied

#         return super(FleetBaseView, self).dispatch(*args, **kwargs)


# class FleetList(FleetBaseView, ListView):

#     model = Fleet
#     template_name = "fleet/list.html"

#     def get_queryset(self):
#         return Fleet.objects.all()


# class FleetCreate(FleetBaseView, CreateView):

#     model = Fleet
#     template_name = "fleet/form.html"
#     success_url = reverse_lazy('fleet:list')
#     fields = ['name', 'category', 'description']

#     def form_valid(self, form):
#         messages.success(self.request, u"Veículo cadastrado com sucesso.")

#         return super(FleetCreate, self).form_valid(form)


# class FleetUpdate(FleetBaseView, UpdateView):

#     model = Fleet
#     template_name = "fleet/form.html"
#     success_url = reverse_lazy('fleet:list')
#     fields = ['name', 'category', 'description']

#     def form_valid(self, form):
#         messages.success(self.request, u"Veículo alterado com sucesso.")

#         return super(FleetUpdate, self).form_valid(form)

src/app/fleet/templates/fleet/form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% include "form_error.html" %}
        <div class="col-md-6 col-md-offset-3 login-register">
            <div class="panel panel-default">
                <div class="panel-heading"><strong>Novo veículo</strong></div>
                <div class="panel-body">
                    <div class="form-group {% if form.name.errors %}has-error{% endif %}">
                        <label class="control-label">{{ form.name.label }} {% if form.name.field.required %}*{% endif %}</label>
                        {% render_field form.name class="form-control" %}
                        {% include "field_error.html" with field=form.name %}
                    </div>
                    <div class="form-group {% if form.category.errors %}has-error{% endif %}">
                        <label class="control-label">{{ form.category.label }}{% if form.category.field.required %}*{% endif %}</label>
                        {% render_field form.category class="form-control" %}
                        {% include "field_error.html" with field=form.category %}
                    </div>
                    <div class="form-group {% if form.description.errors %}has-error{% endif %}">
                        <label class="control-label">{{ form.description.label }}{% if form.description.field.required %}*{% endif %}</label>
                        {% render_field form.description class="form-control" %}
                        {% include "field_error.html" with field=form.description %}
                    </div>
                    <a href="{% url 'fleet:list' %}" class="btn btn-default"><i class="fa fa-reply"></i> Voltar</a  >
                    <button type="reset" class="btn btn-default"><i class="fa fa-eraser"></i> Limpar</button  >
                    <button type="submit" class="btn btn-success pull-right"><i class="fa fa-check"></i> Salvar</button>
                    <div class="clearfix"></div>
                    <p class="text-muted pull-right">* Campos Obrigatórios</p>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

src/app/fleet/templates/fleet/list.html
{% extends "base.html" %}

{% block content %}
    <div class="form-group pull-right">
        <a href="{% url 'fleet:create' %}" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Cadastrar novo veículo</a>
    </div>
    <div class="clearfix"></div>
    {% if object_list %}
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Categoria</th>
                    <th>Descrição</th>
                    <th>Alugado?</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td><a href="{% url 'fleet:update' obj.id %}">{{ obj.name }}</a></td>
                        <td>{{ obj.get_category_display }}</td>
                        <td>{{ obj.description }}</td>
                        <td class="rented">
                            {% if obj.is_rented %}
                                <p class="is-rented"><i class="fa fa-check-circle"></i></p>
                            {% else %}
                                <p class="not-rented"><i class="fa fa-times-circle"></i></p>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            <p>Nenhum registro encontrado.</p>
        </div>
    {% endif %}
{% endblock content %}