src/app/customer/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView
from app.customer import views


urlpatterns = [
    url(r'^registro/$', views.CustomerCreate.as_view(), name='register'),
]

src/app/dashboard/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from app.dashboard import views

urlpatterns = [
    url(r'^$', login_required(TemplateView.as_view(
        template_name='dashboard/index.html')), name='index'),
    url(r'^meus-alugueis$', login_required(views.RentACarList.as_view()), name='rent')
]

src/app/rentacar/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from app.rentacar import views

urlpatterns = [
    url(r'^alugar$', login_required(views.RentACarView.as_view()),
        name='create'),
    url(r'^devolver$', login_required(views.RentACarGiveBackView.as_view()),
        name='give-back'),
]

src/lemonade/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from app.core.views import Home

# handler500 = 'app.core.views.page_500'
handler404 = 'app.core.views.page_404'
handler403 = 'app.core.views.page_403'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^clientes/', include('app.customer.urls', namespace='customer')),
    url(r'^administracao/', include('app.dashboard.urls',
        namespace='dashboard')),
    url(r'^frota/', include('app.fleet.urls', namespace='fleet')),
    url(r'^aluguel/', include('app.rentacar.urls', namespace='rentacar')),
    url(r'^login$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/'},
        name='logout'),
    url(r'^api/v1', include('app.api.v1.urls', namespace='api-v1')),
    url(r'^$', Home.as_view(), name='index'),
]

src/app/core/models.py
from django.db import models

# Create your models here.

src/app/fleet/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from app.core.flags import CATEGORY_CHOICES


class Fleet(models.Model):

    class Meta:
        app_label = u'fleet'
        verbose_name = 'Frota'
        verbose_name_plural = 'Frotas'

    vehicle_name = models.CharField(verbose_name=u'Nome', max_length=255)
    category = models.CharField(verbose_name=u'Categoria', max_length=10,
        choices=CATEGORY_CHOICES)
    description = models.TextField(verbose_name=u'Descrição', max_length=1000,
        null=True, blank=True)
    is_rented = models.BooleanField(verbose_name=u'Está alugado?',
        default=False)

    def _validate_cnh_type(self, customer):
        can_rent = False

        if self.category == 'motorcycle' and 'A' in customer.cnh_type:
            can_rent = True
        elif self.category == 'car' and 'B' in customer.cnh_type:
            can_rent = True
        elif self.category == 'utility' and 'C' in customer.cnh_type:
            can_rent = True
        elif (self.category == 'truck' and
            ('D' in customer.cnh_type or 'E' in customer.cnh_type)):
            can_rent = True

        return can_rent

    def can_rent(self, customer):
        if not self.is_rented:
            return self._validate_cnh_type(customer)

    def __unicode__(self):
        return self.vehicle_name

src/app/core/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.list import ListView
from app.fleet.models import Fleet

def page_403(request):
    response = render(request, '403.html')
    response.status_code = 403

    return response

class Home(ListView):

    template_name='fleet_list.html'

    def get_queryset(self, *args, **kwargs):
        return Fleet.objects.all()

src/app/core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Home{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    </head>
    <body>
        {% block body %}
        <header>
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'index' %}">Locadora de Veículos</a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
                        {% if request.user.is_authenticated and request.user.customer %}
                            <ul class="nav navbar-nav">
                                <li><a href="{% url 'dashboard:index' %}">Administração</a></li>
                                <li><a href="{% url 'dashboard:rent' %}">Meus aluguéis</a></li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="{% url 'logout' %}">Sair</a></li>
                            </ul>
                        {% else %}
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="{% url 'customer:register' %}">Cadastro</a></li>
                                <li><a href="{% url 'login' %}">Login</a></li>
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </header>
        <section class="container content">
            {% include "messages.html" %}
            {% block content %}
                <p class="text-center">Bem-vindo!</p>
            {% endblock content %}
        </section>
        <footer>
            <nav class="navbar navbar-default navbar-fixed-bottom">
                <div class="container">
                    <p class="text-muted text-center footer-p">Copyright&copy; 2016 Adriano Margarin. Todos os direitos reservados.</p>
                </div>
            </nav>
        </footer>
        {% endblock body %}

        <div class="javascripts">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
            <script src="{% static 'js/jquery.maskedinput.js' %}"></script>
            <script src="{% static 'js/customer.js' %}"></script>
        </div>
    </body>
</html>

src/app/core/templates/field_error.html
{% for error in field.errors %}
    <p class="error-field">{{ error }}</p>
{% endfor %}

src/app/core/templates/fleet_list.html
{% extends "base.html" %}

{% block title %}Página Inicial{% endblock title %}

{% block content %}
    {% if object_list %}
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Categoria</th>
                    <th>Descrição</th>
                    <th class="rented">Alugado?</th>
                    <th class="rented">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td>{{ obj.vehicle_name }}</td>
                        <td>{{ obj.get_category_display }}</td>
                        <td>{{ obj.description }}</td>
                        <td class="rented">
                            {% if obj.is_rented %}
                                <p class="is-rented"><i class="fa fa-check-circle"></i></p>
                            {% else %}
                                <p class="not-rented"><i class="fa fa-times-circle"></i></p>
                            {% endif %}
                        </td>
                        <td>
                            <form method="POST" action="{% url 'rentacar:create' %}">
                                {% csrf_token %}
                                <input type="hidden" name="fleet_id" value="{{ obj.id }}">
                                <button type="submit" class="btn btn-primary btn-block" {% if not request.user.customer or obj.is_rented %}disabled{% endif %}><i class="fa fa-car"></i> Alugar</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            Nenhum veículo encontrado.
        </div>
    {% endif %}
{% endblock content %}

src/app/core/templates/form_error.html
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">{{ error }}</div>
{% endfor %}

src/app/core/templates/login.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block title %}Registro{% endblock title %}

{% block content %}
    <div class="col-md-6 col-md-offset-3 login-register">
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Acessar</strong></div>
            <div class="panel-body">
                <form method="POST">
                    {% csrf_token %}
                    {% include "form_error.html" %}
                    <div class="form-group {% if form.username.errors %}has-error{% endif %}">
                        <label class="control-label">Usuário {% if form.username.field.required %}*{% endif %}</label>
                        {% render_field form.username class="form-control" %}
                        {% include "field_error.html" with field=form.username %}
                    </div>
                    <div class="form-group {% if form.password.errors %}has-error{% endif %}">
                        <label class="control-label">Senha{% if form.password.field.required %}*{% endif %}</label>
                        {% render_field form.password class="form-control" %}
                        {% include "field_error.html" with field=form.password %}
                    </div>
                    <button type="reset" class="btn btn-default"><i class="fa fa-eraser"></i> Limpar</button  >
                    <button type="submit" class="btn btn-success pull-right"><i class="fa fa-unlock-alt"></i> Acessar</button>
                    <div class="clearfix"></div>
                    <p class="text-muted pull-right">* Campos Obrigatórios</p>
                    <p>Não possui conta? <a href="{% url 'customer:register' %}"> Registe-se agora.</a></p>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

src/app/core/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}