src/app/dashboard/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from app.dashboard import views

urlpatterns = [
    url(r'^$', login_required(TemplateView.as_view(
        template_name='dashboard/index.html')), name='index'),
    url(r'^meus-alugueis$', login_required(views.RentACarList.as_view()), name='rent')
]

src/app/rentacar/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from app.rentacar import views

urlpatterns = [
    url(r'^alugar$', login_required(views.RentACarView.as_view()),
        name='create'),
    url(r'^devolver$', login_required(views.RentACarGiveBackView.as_view()),
        name='give-back'),
]

src/lemonade/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from app.core.views import Home

# handler500 = 'app.core.views.page_500'
handler404 = 'app.core.views.page_404'
handler403 = 'app.core.views.page_403'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^clientes/', include('app.customer.urls', namespace='customer')),
    url(r'^administracao/', include('app.dashboard.urls',
        namespace='dashboard')),
    url(r'^frota/', include('app.fleet.urls', namespace='fleet')),
    url(r'^aluguel/', include('app.rentacar.urls', namespace='rentacar')),
    url(r'^login$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/'},
        name='logout'),
    url(r'^api/v1', include('app.api.v1.urls', namespace='api-v1')),
    url(r'^$', Home.as_view(), name='index'),
]

src/app/dashboard/models.py
from django.db import models

# Create your models here.

src/app/fleet/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from app.core.flags import CATEGORY_CHOICES


class Fleet(models.Model):

    class Meta:
        app_label = u'fleet'
        verbose_name = 'Frota'
        verbose_name_plural = 'Frotas'

    vehicle_name = models.CharField(verbose_name=u'Nome', max_length=255)
    category = models.CharField(verbose_name=u'Categoria', max_length=10,
        choices=CATEGORY_CHOICES)
    description = models.TextField(verbose_name=u'Descrição', max_length=1000,
        null=True, blank=True)
    is_rented = models.BooleanField(verbose_name=u'Está alugado?',
        default=False)

    def _validate_cnh_type(self, customer):
        can_rent = False

        if self.category == 'motorcycle' and 'A' in customer.cnh_type:
            can_rent = True
        elif self.category == 'car' and 'B' in customer.cnh_type:
            can_rent = True
        elif self.category == 'utility' and 'C' in customer.cnh_type:
            can_rent = True
        elif (self.category == 'truck' and
            ('D' in customer.cnh_type or 'E' in customer.cnh_type)):
            can_rent = True

        return can_rent

    def can_rent(self, customer):
        if not self.is_rented:
            return self._validate_cnh_type(customer)

    def __unicode__(self):
        return self.vehicle_name

src/app/dashboard/views.py
# -*- coding: utf-8 -*-

from django.views.generic.list import ListView
from app.rentacar.models import RentACar


class RentACarList(ListView):

    model = RentACar
    template_name = "dashboard/list-rent.html"

    def get_queryset(self):
        return RentACar.objects.filter(customer=self.request.user.customer)

src/app/dashboard/templates/dashboard/index.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block title %}Administração{% endblock title %}

{% block content %}
    <p class="text-center">Bem-vindo, {{ request.user.get_full_name|default:request.user.username }}</p>
{% endblock content %}

src/app/dashboard/templates/dashboard/list-rent.html
{% extends "base.html" %}

{% block title %}Página Inicial{% endblock title %}

{% block content %}
    {% if object_list %}
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Categoria</th>
                    <th>Descrição</th>
                    <th>Km Rodado</th>
                    <th class="rented-give-back">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td>{{ obj.vehicle.vehicle_name }}</td>
                        <td>{{ obj.vehicle.get_category_display }}</td>
                        <td>{{ obj.vehicle.description }}</td>
                        <td>{{ obj.mileage_rotated|default:"" }}</td>
                        <td>
                            {% if not obj.is_back %}
                                <form method="POST" action="{% url 'rentacar:give-back' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="rent_id" value="{{ obj.id }}">
                                    <div class="input-group">
                                        <input type="number" step="0.10" name="mileage_rotated" class="form-control">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-danger"><i class="fa fa-car"></i> Devolver</button>
                                        </span>
                                    </div>
                                </form>
                            {% else %}
                                Veículo já devolvido.
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            Nenhum aluguel encontrado.
        </div>
    {% endif %}
{% endblock content %}